### ISSUE TITLE
Basic architecture

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/pascalabcnet.cecil#3]
## TODO
- [x] Copy the current code of `PascalABCCompiler.NETGenerator.ILConverter` into a separate file
  - Note that it shouldn't go to the Toolkit project. Just keep it in the same project as the original file lives in.
- [x] Extract a basic interface out of it, allow the compiler to switch between old and new implementation based on an environment variable (make our new version the default for now)
- [x] Make sure the CI works after that
