### ISSUE TITLE
Toolkit

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/pascalabcnet.cecil#4]
## Depends on
- [x] #2 
- [x] #3 

## TODO
- [ ] Replace basic Reflection.Emit types such as `AssemblyBuilder`, `ModuleBuilder`, `TypeBuilder` with our own mocks (that will just delegate the calls to Reflection.Emit types for now). These mocks should go to the Cecil Toolkit project.
  - [x] `AssemblyBuilder`
  - [ ] `AssemblyBuilderAccess`
  - [ ] `AssemblyName`
  - [ ] `ConstructorInfo`
  - [ ] `CustomAttributeBuilder`
  - [ ] `ImageFileMachine`
  - [ ] `MethodBuilder`
  - [ ] `ModuleBuilder`
  - [ ] `PEFileKinds`
  - [ ] `PortableExecutableKinds`
- [ ] Drop `ToolkitAssemblyBuilder::CreateInstance` and the whole ability to create a `RunOnly` assembly in the code generator
- [ ] Process exceptions thrown from `ToolkitAssemblyBuilder::Save` – should be some portable exceptions
- [ ] Make sure the new `ILConverter` doesn't rely on raw Reflection.Emit anymore (and uses mocks for everything)
- [ ] Migrate the Cecil Toolkit mocks to Cecil, while keeping the public API surface the same
- [ ] At this point, the Toolkit project may detach from the project
- [ ] Also, we may consider merging back to the upstream
